name: Build APK (Docker)

on:
  push:
    branches: [ docker-build ]
  workflow_dispatch:

jobs:
  build-in-docker:
    runs-on: ubuntu-latest
    
    container:
      image: ghcr.io/cirruslabs/flutter:stable
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Flutter doctor
      run: flutter doctor -v
      
    - name: Get dependencies
      run: flutter pub get
      
    - name: Build APK (Split per ABI)
      run: flutter build apk --release --split-per-abi
      
    - name: Get version
      id: version
      run: |
        VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //' | sed 's/+.*//')
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
    - name: Prepare release files
      run: |
        mkdir -p build/release
        cp build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk build/release/mini-translate-v${{ steps.version.outputs.version }}-armeabi-v7a.apk
        cp build/app/outputs/flutter-apk/app-arm64-v8a-release.apk build/release/mini-translate-v${{ steps.version.outputs.version }}-arm64-v8a.apk
        cp build/app/outputs/flutter-apk/app-x86_64-release.apk build/release/mini-translate-v${{ steps.version.outputs.version }}-x86_64.apk
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: apk-docker-build
        path: build/release/*.apk
        retention-days: 30
